# Generated by Django 5.1.12 on 2025-09-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="To be encrypted in production",
                max_length=150,
                verbose_name="first name",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="To be encrypted in production",
                max_length=150,
                verbose_name="last name",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True, help_text="To be encrypted in production", max_length=20
            ),
        ),
    ]
