# Generated by Django 5.1.12 on 2025-09-17 12:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExcelUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="excel_uploads/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["xls", "xlsx"]
                            )
                        ],
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file_hash",
                    models.CharField(
                        help_text="SHA256 hash for duplicate detection",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("file_size", models.BigIntegerField()),
                ("sheet_count", models.IntegerField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excel_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ExcelData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sheet_name", models.CharField(max_length=255)),
                ("sheet_index", models.IntegerField()),
                (
                    "row_data",
                    models.JSONField(
                        default=dict, help_text="Stores headers and rows as JSON"
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sheets",
                        to="excel_manager.excelupload",
                    ),
                ),
            ],
            options={
                "ordering": ["sheet_index"],
            },
        ),
        migrations.AddIndex(
            model_name="excelupload",
            index=models.Index(
                fields=["user", "-uploaded_at"], name="excel_manag_user_id_86c27f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="excelupload",
            index=models.Index(fields=["status"], name="excel_manag_status_4c661b_idx"),
        ),
        migrations.AddIndex(
            model_name="excelupload",
            index=models.Index(
                fields=["file_hash"], name="excel_manag_file_ha_644adf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="exceldata",
            unique_together={("upload", "sheet_index")},
        ),
    ]
