# Generated by Django 5.1.12 on 2025-09-17 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("excel_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "validation_result",
                    models.JSONField(
                        help_text="Structured response: {issues, summary, severity}"
                    ),
                ),
                ("issues_found", models.IntegerField(default=0)),
                ("suggestions", models.TextField(blank=True)),
                (
                    "ai_metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Stores tokens, cost, model, response_time",
                    ),
                ),
                ("validated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "excel_upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_validations",
                        to="excel_manager.excelupload",
                    ),
                ),
            ],
            options={
                "ordering": ["-validated_at"],
                "indexes": [
                    models.Index(
                        fields=["excel_upload", "-validated_at"],
                        name="excel_manag_excel_u_105e8c_idx",
                    )
                ],
            },
        ),
    ]
